import { createServer } from "node:net";

export const WEB_BASE_PORT = 3000;
export const AGENT_BASE_PORT = 8787;
export const INSPECTOR_BASE_PORT = 9229;
export const MAX_SLOT = 99;

export function portsForSlot(slot) {
  return {
    web: WEB_BASE_PORT + slot,
    agent: AGENT_BASE_PORT + slot,
    inspector: INSPECTOR_BASE_PORT + slot,
  };
}

export function isPortFree(port) {
  return new Promise((resolve) => {
    const server = createServer();
    server.once("error", () => resolve(false));
    server.once("listening", () => server.close(() => resolve(true)));
    server.listen(port, "0.0.0.0");
  });
}

// Claims map a worktree path to its slot. Claims whose directory is gone are dropped first.
export async function allocateSlot({ claims, worktreePath, isLive, isFree = isPortFree }) {
  const live = Object.fromEntries(Object.entries(claims).filter(([path]) => isLive(path)));
  if (live[worktreePath] !== undefined) return { slot: live[worktreePath], claims: live };

  const taken = new Set(Object.values(live));
  for (let slot = 1; slot <= MAX_SLOT; slot += 1) {
    if (taken.has(slot)) continue;
    const ports = Object.values(portsForSlot(slot));
    const free = await Promise.all(ports.map((port) => isFree(port)));
    if (free.every(Boolean)) return { slot, claims: { ...live, [worktreePath]: slot } };
  }
  throw new Error(`No free worktree slot between 1 and ${MAX_SLOT}.`);
}

export function releaseSlot(claims, worktreePath) {
  return Object.fromEntries(Object.entries(claims).filter(([path]) => path !== worktreePath));
}

// Sets KEY=value lines, replacing an existing line (even an empty template value) or appending.
export function setEnvValues(content, values) {
  let result = content;
  for (const [key, value] of Object.entries(values)) {
    const line = `${key}=${value}`;
    const pattern = new RegExp(`^${key}=.*$`, "m");
    if (pattern.test(result)) {
      result = result.replace(pattern, () => line);
    } else {
      result = `${result}${result === "" || result.endsWith("\n") ? "" : "\n"}${line}\n`;
    }
  }
  return result;
}

export function parseEnv(content) {
  const entries = {};
  for (const line of content.split("\n")) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (match) entries[match[1]] = match[2];
  }
  return entries;
}

export function worktreeEnvContent(slot) {
  const ports = portsForSlot(slot);
  return [
    "# Generated by scripts/worktree.mjs. Ignored by git.",
    `WORKTREE_SLOT=${slot}`,
    `WEB_PORT=${ports.web}`,
    `AGENT_PORT=${ports.agent}`,
    `AGENT_INSPECTOR_PORT=${ports.inspector}`,
    "",
  ].join("\n");
}
